"""add products catalogue

Revision ID: 070bdd944031
Revises: f69828b34e88
Create Date: 2026-09-11 11:05:27.739116
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '070bdd944031'
down_revision: str | None = 'f69828b34e88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entitlements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    # ### end Alembic commands ###

    _seed_launch_catalogue()


def _seed_launch_catalogue() -> None:
    """Insert the launch catalogue.

    These are *starting* prices, not constants: once the row exists the database
    is the only authority and an operator changes it without a deploy. The ids
    are fixed rather than random so the same product carries the same id in every
    environment, which makes a support question answerable.
    """
    products = sa.table(
        'products',
        sa.column('id', sa.Uuid()),
        sa.column('code', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.Text()),
        sa.column('price_amount', sa.Integer()),
        sa.column('currency', sa.String()),
        sa.column('entitlements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql')),
        sa.column('is_active', sa.Boolean()),
        sa.column('is_featured', sa.Boolean()),
        sa.column('sort_order', sa.Integer()),
    )

    op.bulk_insert(
        products,
        [
            {
                'id': uuid.UUID('0f1d6b9c-2a54-4d7e-9c3b-5e8a1f0d4c21'),
                'code': 'CAREER_READING',
                'name': 'Công danh & Sự nghiệp',
                'description': (
                    'Môi trường làm việc hợp với bạn, cách bạn ra quyết định khi bị dồn, '
                    'và vì sao có những giai đoạn bạn muốn đổi hướng. Đọc từ cung Quan Lộc '
                    'cùng tam phương tứ chính của nó.'
                ),
                'price_amount': 99000,
                'currency': 'VND',
                'entitlements': ['CAREER_READING'],
                'is_active': True,
                'is_featured': False,
                'sort_order': 10,
            },
            {
                'id': uuid.UUID('7b2e4a18-9c60-4f3d-8a15-2d9c6e7b0a34'),
                'code': 'FINANCE_READING',
                'name': 'Tài chính',
                'description': (
                    'Tiền vào và ra theo nhịp nào trong lá số bạn: tích lũy đều hay lên '
                    'xuống theo đợt, và điều gì thường khiến bạn giữ được hoặc mất đi. '
                    'Đọc từ cung Tài Bạch cùng tam phương tứ chính của nó.'
                ),
                'price_amount': 99000,
                'currency': 'VND',
                'entitlements': ['FINANCE_READING'],
                'is_active': True,
                'is_featured': False,
                'sort_order': 20,
            },
            {
                'id': uuid.UUID('c4a8f36d-5e21-4b90-9f7c-1a3b8d2e6c05'),
                'code': 'LOVE_READING',
                'name': 'Tình yêu & Hôn nhân',
                'description': (
                    'Kiểu người bạn bị thu hút, điều bạn thực sự cần trong một mối quan hệ '
                    'dài, và điểm dễ va chạm. Đọc từ cung Phu Thê cùng tam phương tứ chính '
                    'của nó.'
                ),
                'price_amount': 99000,
                'currency': 'VND',
                'entitlements': ['LOVE_READING'],
                'is_active': True,
                'is_featured': False,
                'sort_order': 30,
            },
            {
                'id': uuid.UUID('e9051c7a-3f84-42b6-8d0e-7c6b5a4f9e18'),
                'code': 'FULL_LIFETIME_READING',
                'name': 'Trọn đời',
                'description': (
                    'Toàn bộ các phần luận giải, gồm cả đại vận và lưu niên, cộng quyền '
                    'xuất PDF. Mua một lần, đọc lại bất cứ lúc nào.'
                ),
                'price_amount': 250000,
                'currency': 'VND',
                'entitlements': ['FULL_LIFETIME_READING', 'PDF_EXPORT'],
                'is_active': True,
                'is_featured': True,
                'sort_order': 40,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
