"""record convention profile on charts

Revision ID: 5679dee8ebe7
Revises: 070bdd944031
Create Date: 2026-09-11 12:05:19.643537
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5679dee8ebe7'
down_revision: str | None = '070bdd944031'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Record which convention profile each chart was built under.

    Nullable on purpose: charts created before the convention layer existed
    genuinely do not know which rules produced them, and writing a profile name
    onto them would be a lie. ``needs_recalculation`` treats NULL as "predates
    the conventions" rather than as a missing value to be backfilled.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('convention_profile', sa.String(length=64), nullable=True))
    op.add_column('charts', sa.Column('convention_version', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_charts_convention_profile'), 'charts', ['convention_profile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charts_convention_profile'), table_name='charts')
    op.drop_column('charts', 'convention_version')
    op.drop_column('charts', 'convention_profile')
    # ### end Alembic commands ###
