"""initial schema: users and charts

Revision ID: f69828b34e88
Revises: 
Create Date: 2026-09-10 18:01:35.763825
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'f69828b34e88'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('charts',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('relationship_label', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('calendar_type', sa.String(length=8), nullable=False),
    sa.Column('birth_day', sa.Integer(), nullable=False),
    sa.Column('birth_month', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('birth_hour', sa.Integer(), nullable=False),
    sa.Column('birth_minute', sa.Integer(), nullable=False),
    sa.Column('is_leap_month', sa.Boolean(), nullable=False),
    sa.Column('birth_place', sa.String(length=160), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('tz_offset', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('engine_stage', sa.String(length=16), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('chart_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_idempotency_key'), 'charts', ['idempotency_key'], unique=True)
    op.create_index('ix_charts_user_created', 'charts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_charts_user_id'), 'charts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charts_user_id'), table_name='charts')
    op.drop_index('ix_charts_user_created', table_name='charts')
    op.drop_index(op.f('ix_charts_idempotency_key'), table_name='charts')
    op.drop_table('charts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
